# ===============================
# SERVER (Railway ???? IMPORTANT)
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (Railway MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:26669/railway
spring.datasource.username=root
spring.datasource.password=uOrhjdaEjIurGIdUzAYAuhJbmfzztvAU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================
app.jwt.secret=mysecret123
app.jwt.expiration-ms=3600000